spring:
  application:
    name: CinemaPlus

  docker:
    compose:
      lifecycle-management: start_only
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/CinemaPlus
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${MY_WSL_IP:localhost}
      port: 6379
      timeout: 2000ms


  kafka:
    bootstrap-servers: localhost:9092
    admin:
      properties:
        request.timeout.ms: 5000

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    root: INFO
    org.apache.kafka: WARN
    org.apache.zookeeper: WARN
    org.hibernate.SQL: INFO
    com.frytes.cinemaPlus: INFO